### ISSUE TITLE
Mansogram order data

### ISSUE THREAD

**Issue by vulkanus** [mladenplavsic/masongram#10]
Hi,

I have implemented your code, by the way is very cool, but I have noticed that sometimes when we refresh the page, the first  picture (entry date), goes to the 3rd place, then if we refresh again, goes again to the 1st... have you notice that or is only a my own issue?

any way to resolve this issue?

thank you.

**Comment by mladenplavsic** [comment]
Can you please share URL to your example? I haven't noticed this earlier.

**Comment by kodjoe** [comment]
You're welcome @vulkanus
