### ISSUE TITLE
Display past 20 images

### ISSUE THREAD

**Issue by edhathaway** [mladenplavsic/masongram#3]
I have ported your fantastic app over to Joomla! CMS and added the Fancybox3 lightbox. Everything is working perfectly except for the 'Infinite loading' feature. Using my Instagram access token it stops loading images at 20. When I use your access token (from your demo page) it continues to load images past 20 as I scroll down the page. What Instagram API settings are you using (e.g. Sandbox vs. Live, oAuth code, etc.) that may be different than mine? FYI: My Instagram Client app is currently in Sandbox.

I have two working links using my access token;
Joomla website (w/Fancybox3):
http://edhathaway.com/instagram-masonry
Demo page:
http://edhathaway.com/Masonry/

Any assistance or feedback you can provide would be most welcomed. Thank you!

Ed

**Comment by edhathaway** [comment]
Please disregard my question, figured out how to show past the sandbox limitation of 20 pics. Thanks again for your great app!

Ed

**Comment by mladenplavsic** [comment]
Can you please close this issue, and explain how you made it work - it could be helpful for other users of this plugin.

Thanks!

**Comment by edhathaway** [comment]
The only way I was able to show past the Sandbox limitation of the latest 20 Instagram images was to request from Instagram to convert my Client App to the **'LIVE'** mode. This request took several days to be approved and I'm told an approval has a 50/50 percent chance of being approved or not.
