### ISSUE TITLE
Mobile devices

### ISSUE THREAD

**Issue by edhathaway** [mladenplavsic/masongram#4]
If you set the 'count' setting to ten (or any value) and view it on mobile device, that is all that will show regardless how many times you attempt to scroll down the page. The only way it will show past your original 'count' or images is to click onto the 'Instagram' button of the last image. It will open up a new browser window to your Instagram post and when you return to MasonGram, the next series of 'count' images will then show. You have to do this at the end of every series of 'count' images to continue to view additional images.

The mobile device tested is Android OS using every installed browser (the default browser, Chrome and Firefox). Could there be a fix/patch to correct this? Thanks!

**Comment by edhathaway** [comment]
Ok, figured out how to get around this issue. Had to set the 'offset' value to '100' to achieve a smooth continues display of images when scrolling down the mobile device page. This value (100) does put a bit of an image loading lag on large screen devices (laptops, desktops) so I'll just play around with the 'offset' value to find a balance. Thanks again for a great script!

**Comment by mladenplavsic** [comment]
Thanks :)
Be careful, as `offset` is percentage value, `100` means that it will load all batches of images.
It could be that this issue is connected to "throttling" implemented here https://github.com/mladenplavsic/masongram/blob/master/src/js/masongram.js#L83
